### ISSUE TITLE
Auction

### ISSUE THREAD

**Issue by Rafnuss** [Rafnuss/johnstottbirdingday#10]
From @dannolloth 
> Here’s a mockup of how the Auction section can go. Basically, just use the same boxes as the stories section, but change the colour to the blue. Then a simple heading underneath the image saying painting 1 or painting 2 etc.
> I’ll put all the images for the paintings in a new folder on the google drive.
> Jo’s gonna get some wording together for this but I’ll raise an issue when it’s ready to go up.

![image](https://user-images.githubusercontent.com/7571260/115351687-c966a800-a1b6-11eb-8062-bea407946823.png)

**Comment by Rafnuss** [comment]
Hi @dannolloth. 
No problem. I'm looking into the eBay API to see if I can get the picture directly from them. In the meantime, I suggest we use a pagination like that to change with the carousel which is just above. Is that ok for you?
![image](https://user-images.githubusercontent.com/7571260/115351767-e1d6c280-a1b6-11eb-8b0b-ce9e141df60a.png)

**Comment by dannolloth** [comment]
Hey @Rafnuss 
Yeah, the above is great. I only thought about the three boxes (same as story) because there are 6 paintings in total. So two lots of three. But the above is great. It'll be four paintings and then two – unless you can split three/three? I'm happy either way though.
And yes to the rounded corners please.

**Comment by Rafnuss** [comment]
Ok,, is that all the auction? Why not putting directly the 6 then? (on two row)

**Comment by dannolloth** [comment]
Yeah, good shout. Go for it.

**Comment by dannolloth** [comment]
Photos (https://drive.google.com/drive/folders/1gjvbL2nUUC99TboMVsmciHG8jIm_0PFx?usp=sharing) and copy (https://drive.google.com/file/d/1685B4lj-iGL_hVvZR5BhQcIGw3VPMDll/view?usp=sharing) are now in the google drive ready for adding.

**Comment by Rafnuss** [comment]
@dannolloth let me know what you think.

**Comment by dannolloth** [comment]
Looks great – I'm happy, but will check and see what Jo thinks.

**Comment by Rafnuss** [comment]
I'll close this as I think I've done all way requested. @dannolloth feel free to re-open it if there is anything more to add (rather than opening a new one)
