### ISSUE TITLE
Photos for stories in wrong places

### ISSUE THREAD

**Issue by dannolloth** [Rafnuss/johnstottbirdingday#12]
<img width="306" alt="image" src="https://user-images.githubusercontent.com/81353383/116084603-dfcca200-a695-11eb-9b76-5abafe10d9b6.png">
This image should go with Chris Walley's story

**Comment by dannolloth** [comment]
<img width="306" alt="image" src="https://user-images.githubusercontent.com/81353383/116084778-0985c900-a696-11eb-932d-ea30497bbc11.png">

This image should go with Robert Kelsh's story

**Comment by Rafnuss** [comment]
So, no pictures for David Jones, right?
--
Raphaël.

**Comment by dannolloth** [comment]
Yeah for now. I'm looking into it.
