### ISSUE TITLE
Bird race page

### ISSUE THREAD

**Issue by dannolloth** [Rafnuss/johnstottbirdingday#14]
Hey Raf,
Thanks for doing those other things.
Do you know when you'll be able to make the bird race page live?

**Comment by Rafnuss** [comment]
I was thinking of waiting for the day to start and the first checklists to
be submitted. Or do you think we should have an empty map first?
It might also depend on if I'm doing the bird race or not. If I'm in the
field, it might be difficult to compete...
--
Raphaël.

**Comment by dannolloth** [comment]
Just chatted with Jo and we think put it live now. 
Hope that's ok.
D

**Comment by Rafnuss** [comment]
Sure, no pb. I didn't put it up as I don't really find the page interesting... (very empty)
