### ISSUE TITLE
Safari viewing

### ISSUE THREAD

**Issue by dannolloth** [Rafnuss/johnstottbirdingday#2]
Hey Raf,
Safari is still a bit glitchy. The main things are:

- The map in the Competition/Bird race section
- Stories ( the photos are huuuuuuuge)

**Comment by Rafnuss** [comment]
I correct for the photos, should be good now.
The map is working fine on my safari. (have to wait a few seconds) Can yous describe the problem?

**Comment by dannolloth** [comment]
All good – you've fixed both these issues. Stories and map fine now.
