### ISSUE TITLE
Text changes

### ISSUE THREAD

**Issue by dannolloth** [Rafnuss/johnstottbirdingday#3]
Change "HOW YOU CAN TAKE PART?" to "HOW TO TAKE PART"

so change you and remove the ?

**Comment by dannolloth** [comment]
Change "8th May" to "8 May"

remove "th" from all instances of the date.

**Comment by Rafnuss** [comment]
Resolved with 61ac000ba8538476af9c8930f0d2d7150a98c7ca.
