### ISSUE TITLE
Photo change in the 'Taking part' section

### ISSUE THREAD

**Issue by dannolloth** [Rafnuss/johnstottbirdingday#5]
Could you change the red bird picture to this https://unsplash.com/photos/Zo_RjXxOvsA
 Bee eater.

The current one looks too wintery. We need a spring summer one.

**Comment by Rafnuss** [comment]
Yeah, it would be indeed nice more colourful, but I find the quality not really good on this bee-eater. 
I can offer to use some of my pictures:
https://ebird.org/media/catalog?taxonCode=ncbeat1&mediaType=p&searchField=user&includeUnconfirmed=T&userId=USER497615&q=Rapha%C3%ABl%20Nussbaumer&species=Northern%20Carmine%20Bee-eater%20-%20Merops%20nubicus. Or feel free to take any picture from https://ebird.org/media/catalog?mediaType=p&sort=rating_rank_desc&searchField=user&includeUnconfirmed=T&userId=USER497615&q=Rapha%C3%ABl%20Nussbaumer.

Do you have access to the bird album on flikr? There quite nice picture there too.

**Comment by dannolloth** [comment]
This one is perfect. Add it in!
 ML250750661<https://macaulaylibrary.org/asset/250750661>


Dan Nolloth | Designer

From: Raphaël Nussbaumer ***@***.***>
Reply to: Rafnuss/johnstottbirdingday ***@***.***>
Date: Thursday, 1 April 2021 at 13:26
To: Rafnuss/johnstottbirdingday ***@***.***>
Cc: dannolloth ***@***.***>, Author ***@***.***>
Subject: Re: [Rafnuss/johnstottbirdingday] Photo change in the 'Taking part' section (#5)


Yeah, it would be indeed nice more colourful, but I find the quality not really good on this bee-eater.
I can offer to use some of my pictures:
https://ebird.org/media/catalog?taxonCode=ncbeat1&mediaType=p&searchField=user&includeUnconfirmed=T&userId=USER497615&q=Rapha%C3%ABl%20Nussbaumer&species=Northern%20Carmine%20Bee-eater%20-%20Merops%20nubicus. Or feel free to take any picture from https://ebird.org/media/catalog?mediaType=p&sort=rating_rank_desc&searchField=user&includeUnconfirmed=T&userId=USER497615&q=Rapha%C3%ABl%20Nussbaumer.

Do you have access to the bird album on flikr? There quite nice picture there too.
