### ISSUE TITLE
Missing links

### ISSUE THREAD

**Issue by Rafnuss** [Rafnuss/johnstottbirdingday#8]
- [x] facebook
- [x] instagram
- [x] twitter
- [x] donate
- [x] mail

**Comment by dannolloth** [comment]
https://www.facebook.com/groups/284914929692849/

not sure we've got any of the other yet. Will check with Jo

**Comment by Rafnuss** [comment]
@dannolloth , just to remind you about this.

**Comment by dannolloth** [comment]
https://twitter.com/search?q=%23johnstottbirding&src=typed_query

Use above for twitter. It's basically a search for #johnstottbirding. There may be an easier way to do this though...?

**Comment by dannolloth** [comment]
https://www.instagram.com/p/CNUwW5cDsau/?utm_source=ig_web_copy_link

Insta link

**Comment by dannolloth** [comment]
Donate to here:
https://www.arocha.org/en/donation-form-ii/
